### ISSUE TITLE
Validation tool failed - TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by LLeBlanc110** [DOI-USGS/gems-tools-pro#112]
I'm running the Validate Database tool (2.13) on someone else's almost complete GeMS database for a mineral resources map that's required some finagling to get it into GeMS, so this could very easily be user error. I've tried to run the Validate Database tool and at first thought it was failing because the attribute domains were not embedded for GeoMaterials and GeoMaterialConfidence.  After adding those back in, I am still receiving the error message below - 

Validate Database
=====================
Parameters

Input geodatabase or geopackage     C:\Users\LLeBlanc\Documents\MappersHelp\NGGDPP\Deliverables-LL\AL_2023_LeeCounty_1.0-submittal\AL_2023_LeeCounty_1.0\AL_2023_LeeCounty_1.0-database\AL_2023_LeeCounty_1.0.gdb
Output workspace     C:\Users\LLeBlanc\Documents\MappersHelp\NGGDPP\Deliverables-LL\validation-LL
Validate standalone file     
Validate embedded metadata     true
Report errors with _ID, not OBJECTID     false
Skip topology checks     false
Refresh GeoMaterialDict     false
Delete unused Glossary and DataSources rows     false
Compact GDB     true
Open report when done     true
=====================
Messages

Start Time: Wednesday, June 26, 2024 3:54:02 PM
This version of the tool is up to date: GeMS_ValidateDatabase.py, version of 3/28/2024
​
Looking at level 2 compliance
Rule 2.1 - Has required elements: nonspatial tables DataSources, 
        DescriptionOfMapUnits, GeoMaterialDict; feature dataset GeologicMap with 
        feature classes ContactsAndFaults and MapUnitPolys
Rule 2.2 - Required fields within required elements are present and correctly defined
2.3 All MapUnitPolys and ContactsAndFaults based feature classes obey Level 2 topology rules: 
        no internal gaps or overlaps in MapUnitPolys, boundaries of MapUnitPolys are covered by ContactsAndFaults
	No topology found in GeologicMap
		Creating geodatabase for topology - C:\Users\LLeBlanc\Documents\MappersHelp\NGGDPP\Deliverables-LL\validation-LL\Topology.gdb
		Creating feature dataset GeologicMap
		Copying feature classes
		Creating topology GeologicMap_Topology
		Adding topology rules to topology
		Looking at validation results for errors
2.4 All map units in MapUnitPolys have entries in DescriptionOfMapUnits table
2.5 No duplicate MapUnit values in DescriptionOfMapUnits table
2.6 Certain field values within required elements have entries in Glossary table
2.7 No duplicate Term values in Glossary table
2.8 All xxxSourceID values in required elements have entries in DataSources table
2.9 No duplicate DataSources_ID values in DataSources table
​
Looking at level 3 compliance
3.1 Table and field definitions conform to GeMS schema
3.2 All MapUnitPolys and ContactsAndFaults based feature classes obey Level 3 topology rules: 
        no overlaps, self-overlaps, or self-intersections in ContactsAndFaults.
3.3 No missing required values
3.4 No missing terms in Glossary
3.5 No unnecessary terms in Glossary
3.6 No missing sources in DataSources
3.7 No unnecessary sources in DataSources
3.8 No map units without entries in DescriptionOfMapUnits
3.9 No unnecessary map units in DescriptionOfMapUnits
3.10 HierarchyKey values in DescriptionOfMapUnits are unique and well formed
﻿Traceback (most recent call last):
﻿  File "C:\Users\LLeBlanc\Documents\GeMS\GeMS_formatfiles_GSA\GemsToolboxes\gems-tools-pro-2.13\gems-tools-pro-2.13\Scripts\GeMS_ValidateDatabase.py", line 1716, in <module>
﻿    dmu_path = db_dict["DescriptionOfMapUnits"]["catalogPath"]
﻿^^^^^^^^^^^^^^
﻿  File "C:\Users\LLeBlanc\Documents\GeMS\GeMS_formatfiles_GSA\GemsToolboxes\gems-tools-pro-2.13\gems-tools-pro-2.13\Scripts\GeMS_ValidateDatabase.py", line 1636, in main
﻿    #     if result[0] == 1:
﻿                             
﻿  File "C:\Users\LLeBlanc\Documents\GeMS\GeMS_formatfiles_GSA\GemsToolboxes\gems-tools-pro-2.13\gems-tools-pro-2.13\Scripts\GeMS_ValidateDatabase.py", line 854, in rule3_10
﻿    ]
﻿     
﻿TypeError: 'NoneType' object is not iterable

Failed script Validate Database...
Failed to execute (ValidateDatabase).
Failed at Wednesday, June 26, 2024 3:54:17 PM (Elapsed Time: 14.96 seconds)

**Comment by LLeBlanc110** [comment]
I deleted some rows from the DMU and the tool ran with no issues, so figure something must've been wrong with the data.
