### ISSUE TITLE
AttributeError: module 'GeMS_utilityFunctions' has no attribute 'eval_bool'

### ISSUE THREAD

**Issue by aldunn4** [DOI-USGS/gems-tools-pro#71]
I am getting this message with the newest version of the tool.

`This version of the tool is up to date
Metadata not checked. File needs to be in XML format.
Traceback (most recent call last):
  File "O:\Style_and_Standards\DataModels\GeMS\gems-tools-pro-2.11.4\Scripts\GeMS_ValidateDatabase.py", line 1609, in <module>
    ]
  File "O:\Style_and_Standards\DataModels\GeMS\gems-tools-pro-2.11.4\Scripts\GeMS_ValidateDatabase.py", line 1202, in main
    database dictionary. If blank, it is an extension"""
AttributeError: module 'GeMS_utilityFunctions' has no attribute 'eval_bool'

Failed script Validate Database...
Failed to execute (ValidateDatabase).`

**Comment by ethoms-usgs** [comment]
Please see the solution to [Issue 69](https://github.com/DOI-USGS/gems-tools-pro/issues/69) and let me know if it works.

**Comment by aldunn4** [comment]
I removed the toolbox, restarted Pro, and added the toolbox back. Now I get this message:
 
`This version of the tool is up to date
Metadata not checked. File needs to be in XML format.
Refreshing GeoMaterialDict
Replacing GeoMaterial domain
Assigning domain to GeoMaterial
​
Looking at level 2 compliance
Rule 2.1 - Has required elements: nonspatial tables DataSources, 
        DescriptionOfMapUnits, GeoMaterialDict; feature dataset GeologicMap with 
        feature classes ContactsAndFaults and MapUnitPolys
Rule 2.2 - Required fields within required elements are present and correctly defined
2.3 All MapUnitPolys and ContactsAndFaults based feature classes obey Level 2 topology rules: 
        no internal gaps or overlaps in MapUnitPolys, boundaries of MapUnitPolys are covered by ContactsAndFaults
Topology check was skipped
2.4 All map units in MapUnitPolys have entries in DescriptionOfMapUnits table
2.5 No duplicate MapUnit values in DescriptionOfMapUnits table
2.6 Certain field values within required elements have entries in Glossary table
2.7 No duplicate Term values in Glossary table
2.8 All xxxSourceID values in required elements have entries in DataSources table
2.9 No duplicate DataSources_ID values in DataSources table
​
Looking at level 3 compliance
3.1 Table and field definitions conform to GeMS schema
3.2 All MapUnitPolys and ContactsAndFaults based feature classes obey Level 3 topology rules: 
        no ContactsAndFaults overlaps, self-overlaps, or self-intersections.
3.3 No missing required values
3.4 No missing terms in Glossary
3.5 No unnecessary terms in Glossary
3.6 No missing sources in DataSources
3.7 No unnecessary sources in DataSources
3.8 No map units without entries in DescriptionOfMapUnits
3.9 No unnecessary map units in DescriptionOfMapUnits
3.10 HierarchyKey values in DescriptionOfMapUnits are unique and well formed
Traceback (most recent call last):
  File "O:\Style_and_Standards\DataModels\GeMS\gems-tools-pro-master\Scripts\GeMS_ValidateDatabase.py", line 1609, in <module>
    ]
  File "O:\Style_and_Standards\DataModels\GeMS\gems-tools-pro-master\Scripts\GeMS_ValidateDatabase.py", line 1529, in main
    ver_table = db_dict["Version"]["catalogPath"]
ValueError: too many values to unpack (expected 2)

Failed script Validate Database...
Failed to execute (ValidateDatabase).`

**Comment by aldunn4** [comment]
Do you have any insight on the new error I'm getting?

**Comment by ethoms-usgs** [comment]
I apologize, Amy. I had commented those lines out in the latest couple versions but hadn't changed the date in the version string, so you didn't get a warning the tool had been updated. Done now in [v2.12.2](https://github.com/DOI-USGS/gems-tools-pro/releases/tag/v2.12.2)
