### ISSUE TITLE
Validate Database fails when trying to create topology geodatabase

### ISSUE THREAD

**Issue by NCGSBTT** [DOI-USGS/gems-tools-pro#89]
Had this error happen multiple times today on a database that had been validated fine yesterday. I'm not sure why the issue suddenly arose but I have tried validating with previous tool versions and get the same error. I've tried setting up the topology separate (topologically everything is fine) and it still doesn't run. 

This version of the tool is up to date: GeMS_ValidateDatabase.py, version of 10/18/2023
​
Looking at level 2 compliance
Rule 2.1 - Has required elements: nonspatial tables DataSources, 
        DescriptionOfMapUnits, GeoMaterialDict; feature dataset GeologicMap with 
        feature classes ContactsAndFaults and MapUnitPolys
Rule 2.2 - Required fields within required elements are present and correctly defined
2.3 All MapUnitPolys and ContactsAndFaults based feature classes obey Level 2 topology rules: 
        no internal gaps or overlaps in MapUnitPolys, boundaries of MapUnitPolys are covered by ContactsAndFaults
	No topology found in GeologicMap
		Creating geodatabase for topology - G:\LR\GEO\Brennan Trantham\GeMS Stuff\FY22 Draft Deliverables\Dwain Project #8\Blank Gems File Directory\NC_2022_RaleighIsoStruc_1-1-submittal\NC_2022_RaleighIsoStruc_1-1\NC_2022_RaleighIsoStruct_1-1-database\work\Topology.gdb
Traceback (most recent call last):
  File "\\AR-NGNAS01\AR-GIS-Data\GeMS Resources\GeMS TBX\gems-tools-pro-2.12.8\gems-tools-pro-2.12.8\Scripts\GeMS_ValidateDatabase.py", line 1715, in <module>
    if "DescriptionOfMapUnits" in db_dict:
  File "\\AR-NGNAS01\AR-GIS-Data\GeMS Resources\GeMS TBX\gems-tools-pro-2.12.8\gems-tools-pro-2.12.8\Scripts\GeMS_ValidateDatabase.py", line 1462, in main
    cursor.deleteRow()
  File "\\AR-NGNAS01\AR-GIS-Data\GeMS Resources\GeMS TBX\gems-tools-pro-2.12.8\gems-tools-pro-2.12.8\Scripts\GeMS_ValidateDatabase.py", line 339, in check_topology
    and not f.name.lower() in lower_standard
  File "\\AR-NGNAS01\AR-GIS-Data\GeMS Resources\GeMS TBX\gems-tools-pro-2.12.8\gems-tools-pro-2.12.8\Scripts\topology.py", line 219, in make_topology
    gdb_path, topo_mup, topo_caf = create_fd(work_dir, gmap, sr, topo_pair, db_dict)
  File "\\AR-NGNAS01\AR-GIS-Data\GeMS Resources\GeMS TBX\gems-tools-pro-2.12.8\gems-tools-pro-2.12.8\Scripts\topology.py", line 121, in create_fd
    arcpy.CreateFileGDB_management(str(work_dir), "Topology")
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 25915, in CreateFileGDB
    raise e
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 25912, in CreateFileGDB
    retval = convertArcObjectToPythonObject(gp.CreateFileGDB_management(*gp_fixargs((out_folder_path, out_name, out_version), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 512, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: ERROR 999999: Something unexpected caused the tool to fail. Contact Esri Technical Support (http://esriurl.com/support) to Report a Bug, and refer to the error help for potential solutions or workarounds.
Failed to execute (CreateFileGDB).

Failed script Validate Database...
Failed to execute (ValidateDatabase).

**Comment by ethoms-usgs** [comment]
Whops! missed this. Are you still seeing this error?

**Comment by NCGSBTT** [comment]
No worries, I figured it out. For some reason the tool wouldn’t read where
the geodatabase was located. Moving it to a different path got it to work.
